// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#pragma once

#include "auth_info.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace act {

struct AuthReply final {
    int32_t err;
    std::string msg;
    AuthInfo data;

    AuthReply(int32_t err_,
              std::string msg_,
              AuthInfo data_)
    : err(std::move(err_))
    , msg(std::move(msg_))
    , data(std::move(data_))
    {}
};

}  // namespace act
