// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#pragma once

#include <string>

namespace act {

class PushListener {
public:
    virtual ~PushListener() {}

    virtual void onNotify(const std::string & pushMsg) = 0;
};

}  // namespace act
