// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#pragma once

#include <string>
#include <utility>

namespace act {

struct UserInfo final {
    std::string user_name;
    std::string pwd_hash;
    std::string device;

    UserInfo(std::string user_name_,
             std::string pwd_hash_,
             std::string device_)
    : user_name(std::move(user_name_))
    , pwd_hash(std::move(pwd_hash_))
    , device(std::move(device_))
    {}
};

}  // namespace act
