// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#include "native_auth_info.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

native_auth_info::native_auth_info() = default;

native_auth_info::~native_auth_info() = default;

auto native_auth_info::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<native_auth_info>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.token)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto native_auth_info::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<native_auth_info>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mToken))};
}

}  // namespace djinni_generated
