// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#pragma once

#include "djinni_support.hpp"
#include "user_info.hpp"

namespace djinni_generated {

class native_user_info final {
public:
    using CppType = ::act::UserInfo;
    using JniType = jobject;

    using Boxed = native_user_info;

    ~native_user_info();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    native_user_info();
    friend ::djinni::JniClass<native_user_info>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("me/ppxpp/account/auth/UserInfo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mUserName { ::djinni::jniGetFieldID(clazz.get(), "mUserName", "Ljava/lang/String;") };
    const jfieldID field_mPwdHash { ::djinni::jniGetFieldID(clazz.get(), "mPwdHash", "Ljava/lang/String;") };
    const jfieldID field_mDevice { ::djinni::jniGetFieldID(clazz.get(), "mDevice", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
