// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#include "native_auth_reply.hpp"  // my header
#include "Marshal.hpp"
#include "native_auth_info.hpp"

namespace djinni_generated {

native_auth_reply::native_auth_reply() = default;

native_auth_reply::~native_auth_reply() = default;

auto native_auth_reply::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<native_auth_reply>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.err)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.msg)),
                                                           ::djinni::get(::djinni_generated::native_auth_info::fromCpp(jniEnv, c.data)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto native_auth_reply::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<native_auth_reply>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mErr)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mMsg)),
            ::djinni_generated::native_auth_info::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mData))};
}

}  // namespace djinni_generated
