// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#include "native_user_info.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

native_user_info::native_user_info() = default;

native_user_info::~native_user_info() = default;

auto native_user_info::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<native_user_info>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.user_name)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.pwd_hash)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.device)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto native_user_info::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<native_user_info>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUserName)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPwdHash)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mDevice))};
}

}  // namespace djinni_generated
