// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#pragma once

#include "djinni_support.hpp"
#include "push.hpp"

namespace djinni_generated {

class native_push final : ::djinni::JniInterface<::act::Push, native_push> {
public:
    using CppType = std::shared_ptr<::act::Push>;
    using CppOptType = std::shared_ptr<::act::Push>;
    using JniType = jobject;

    using Boxed = native_push;

    ~native_push();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<native_push>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<native_push>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    native_push();
    friend ::djinni::JniClass<native_push>;
    friend ::djinni::JniInterface<::act::Push, native_push>;

};

}  // namespace djinni_generated
