// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

#pragma once

#include "auth_info.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class native_auth_info final {
public:
    using CppType = ::act::AuthInfo;
    using JniType = jobject;

    using Boxed = native_auth_info;

    ~native_auth_info();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    native_auth_info();
    friend ::djinni::JniClass<native_auth_info>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("me/ppxpp/account/auth/AuthInfo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mToken { ::djinni::jniGetFieldID(clazz.get(), "mToken", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
