version: '3'
services:
  account_svr:
    build: ./svr/.
    links:
     - mysql:docker_mysql
     - redis:docker_redis
    ports:
     - "50051:50051"
  mysql:
    image: "mysql:5.7"
    container_name: mysql_5_7
    ports:
     - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
        MYSQL_ROOT_PASSWORD: "root"
  redis:
    image: "redis:5.0.3"
    container_name: redis_5_0_3
    ports:
      - "6379:6379"
  push:
    build: ./push/.
    links:
      - redis:docker_redis
    ports:
     - "50050:50050"