// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

package me.ppxpp.account.auth;

public final class AuthInfo {


    /*package*/ final String mToken;

    public AuthInfo(
            String token) {
        this.mToken = token;
    }

    public String getToken() {
        return mToken;
    }

    @Override
    public String toString() {
        return "AuthInfo{" +
                "mToken=" + mToken +
        "}";
    }

}
