// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

package me.ppxpp.account.auth;

public final class AuthReply {


    /*package*/ final int mErr;

    /*package*/ final String mMsg;

    /*package*/ final AuthInfo mData;

    public AuthReply(
            int err,
            String msg,
            AuthInfo data) {
        this.mErr = err;
        this.mMsg = msg;
        this.mData = data;
    }

    public int getErr() {
        return mErr;
    }

    public String getMsg() {
        return mMsg;
    }

    public AuthInfo getData() {
        return mData;
    }

    @Override
    public String toString() {
        return "AuthReply{" +
                "mErr=" + mErr +
                "," + "mMsg=" + mMsg +
                "," + "mData=" + mData +
        "}";
    }

}
