// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

package me.ppxpp.account.auth;

public abstract class PushListener {
    public abstract void onNotify(String pushMsg);
}
