// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auth.djinni

package me.ppxpp.account.auth;

public final class UserInfo {


    /*package*/ final String mUserName;

    /*package*/ final String mPwdHash;

    /*package*/ final String mDevice;

    public UserInfo(
            String userName,
            String pwdHash,
            String device) {
        this.mUserName = userName;
        this.mPwdHash = pwdHash;
        this.mDevice = device;
    }

    public String getUserName() {
        return mUserName;
    }

    public String getPwdHash() {
        return mPwdHash;
    }

    public String getDevice() {
        return mDevice;
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "mUserName=" + mUserName +
                "," + "mPwdHash=" + mPwdHash +
                "," + "mDevice=" + mDevice +
        "}";
    }

}
